var termsArray = {
  "acetylcholine": "A neurotransmitter that primarily involved in memory and learning; also makes motor movement possible. Too little ACh is linked to Alzheimer's Disease.",
  "action potential": "In a neuron, a brief electrical charge (impulse) that travels down the axon. Generated by the movement of atoms in and out of channels in the axons membrane.",
  "adrenal glands": "A small gland located on top of the kidney. The adrenal glands produce hormones that help control heart rate, blood pressure, the way the body uses food, the levels of minerals such as sodium and potassium in the blood, and other functions particularly involved in stress reactions.",
  "amygdala": "A part of the brain's limbic system that is responsible for detecting fear and preparing for emergency events.",
  "autonomic nervous system": "The part of the nervous system responsible for control of the bodily functions not consciously directed, such as breathing, the heartbeat, and digestive processes.",
  "axon": "A long, slender projection of a nerve cell, or neuron, that conducts electrical impulses away from the neuron's cell body or soma.",
  "brain stem": "Controls the flow of messages between the brain and the rest of the body. It also controls basic body functions such as breathing, swallowing, heart rate, blood pressure, consciousness, and whether one is awake or sleepy. The brain stem consists of the midbrain, pons, and medulla oblongata.",
  "broca's area": "The part of the brain that controls the ability to produce language. Located in the frontal lobe.",
  "ct scan (cat)": "A computed tomography scan uses a combination of X-rays and a computer to create pictures of your organs, bones, and other tissues.",
  "cell body (soma)": "The spherical part of a neuron that contains the nucleus.",
  "central nervous system": "Comprised of the brain and spinal cord, the CNS receives sensory information from the nervous system and controls the body's responses.",
  "cerebellum": "A brain structure located near the brainstem that is responsible for a number of functions including motor skills such as balance, coordination, and posture.",
  "chromosome": "Chromosomes are organized structures of DNA and proteins that are found in cells. Chromosomes contain a single continuous piece of DNA, which contains many genes, regulatory elements and other nucleotide sequences.",
  "dendrite": "A segment of the neuron that receives stimulation in order for the cell to become active. Dendrites conduct electrical messages to the neuron cell body for the cell to function.",
  "dizygotic twins": "Dizygotic twins are siblings who come from seperate egg cells that are fertilized by seperate sperm.",
  "dopamine": "The neurotransmitter that plays a major role in the motivational component of reward-motivated behaviour.",
  "eeg (electroencephalography)": "The practice of placing electrodes on a subject's scalp in order to non-invasively measure the electrical activity of the brain.",
  "endocrine system": "The endocrine system is a series of glands throughout the body that secrete chemicals (hormones) into the bloodstream; hormones, in turn, affect body functions. The endocrine system is often compared to a slow acting nervous system.",
  "endorphins": "Chemicals that help to carry signals across a nerve synapse. Endorphins are the chemical messenger component of neurons. They are released when the body is under stress such as physical pain or intense exercise, and they cause feelings of euphoria and well-being, in addition to reducing pain signals.",
  "frontal lobe": "The part of each hemisphere of the brain located behind the forehead that serves to regulate and mediate the higher intellectual functions. The frontal lobes are important for controlling thoughts, reasoning, and behaviors.",
  "gaba (gamma-aminobutyric acid)": "GABA is an inhibitory neurotransmitter, which means that it weakens or slows down signals.",
  "gene": "A DNA segment that contributes to phenotype/function. ",
  "heritability": "The proportion of observed variation in a particular trait that can be attributed to inherited genetic factors in contrast to environmental ones.",
  "hippocampus": "The part of  the brain's limbic system that is associated with explicit memory.",
  "hormone": "A hormone is a chemical messenger which travels around the body in the bloodstream.",
  "hypothalamus": "The brain structure that controls the pituitary gland and also regulates hunger, thirst, body temperature, and sex drive.",
  "interneurons": "Neurons that enable communication between sensory or motor neurons and the central nervous system (CNS).",
  "kleinfelters/turners syndrome": "Conditions that arise from abnormal sex chromosome counts. Klinefelter's syndrome occurs in males with an extra X chromosome (XXY). Turner's syndrome occurs in females with only one copy of the X chromosome.",
  "lesion": "Damage to body tissue.",
  "limbic system": "The portion of the brain that deals with three key functions: emotions, memories and arousal (or stimulation). Consists of the amygdala, hippocampus, hypothalamus, and thalamus.",
  "medulla oblongata": "The brain structure, located in the brainstem, that is responsible for breathing, blood pressure, circulation, and heart functions.",
  "monozygotic twins": "Monozygotics twins are siblings who come from one fertilized egg cell that splits into two seperate embryos.",
  "motor neuron": "An efferent neuron that originates in the CNS and synapses with muscle fibers to facilitate muscle contraction.",
  "mri": "Magnetic Resonance Imaging uses a strong magnetic field and radio waves to create detailed images of the organs and tissues within the body.",
  "myelin sheath": "An insulating layer that forms around nerves, allowing electrical impulses to transmit quickly and efficiently along the nerve cells.",
  "nature vs. nurture": "In the \"nature vs nurture\" debate, nurture refers to personal experiences (i.e. empiricism or behaviorism). Nature is your genes.",
  "neuron": "An electrically excitable cell that receives, processes, and transmits information through electrical and chemical signals.",
  "neurotransmitter": "A chemical messenger that carries, boosts, and balances signals between neurons, or nerve cells, and other cells in the body.",
  "occipital lobe": "The occipital lobe is the visual processing center of the brain.",
  "parasympathetic nervous system": "The part of the involuntary nervous system that serves to slow the heart rate, increase intestinal and glandular activity, and relax the sphincter muscles.",
  "parietal lobe": "The parietal lobe functions in processing sensory information regarding the location of parts of the body as well as interpreting visual information and processing language and mathematics.",
  "peripheral nervous system": "The PNS consists of all of the nerves that lie outside the brain and spinal cord. It has two parts: the somatic nervous system and the autonomic nervous system.",
  "pet scan": "A positron emission tomography scan uses a special dye containing radioactive glucose tracers to allow doctors to check for diseases.",
  "pituitary gland": "The pituitary gland produces the following hormones and releases them into the bloodstream: adrenocorticotropic hormone, which stimulates the adrenal glands to secrete steroid hormones, principally cortisol. growth hormone, which regulates growth, metabolism and body composition.",
  "pons": "The brain structure involved with relaxation and arousal (consciousness).",
  "reflex arc": "A neural pathway that controls a reflex. The pathway does not pass through the brain.",
  "reticular formation": "The brain structure responsible for the sleep-wake cycle, thus mediating various levels of alertness.",
  "left vs. right hemisphere": "The left side of the brain is responsible for controlling the right side of the body and performing tasks that have to do with logic. The right side of the brain is responsible for controlling the left side of the body and performing tasks that have to do with creativity.",
  "sensory neurons": "Neurons responsible for bringing information from sensory receptors to the central nervous system.",
  "serotonin": "The neurotransmitter that helps regulate mood and social behavior. Low levels of it are linked to depression.",
  "sex glands": "Reproductive gland responsible for producing gametes (sex cells) and sex hormones.",
  "somatic nervous system": "The part of the peripheral nervous system that is responsible for carrying motor and sensory information both to and from the central nervous system. Responsible for voluntary movement.",
  "sympathetic nervous system": "The part of the autonomic nervous system that serves to accelerate the heart rate, constrict blood vessels, and raise blood pressure.",
  "synapse": "A small gap at the end of a neuron that allows a signal to pass from one neuron to the next.",
  "temporal lobe": "The temporal lobe is involved in primary auditory perception, such as hearing. Contains the primary auditory cortex and Wernicke's area.",
  "terminal button": "Located at the end of the neuron and is responsible for sending signals on to other neurons.",
  "thalamus": "A structure in the brain stem that receives sensory information from the nervous system and passes the information to the cerebral cortex and other parts of the brain.",
  "threshold": "The level of strength a stimulus must reach to be detected.",
  "thyroid gland": "A gland located in the neck that secretes two hormones (T3 and T4) that regulate the rates of metabolism, growth, and development.",
  "wernicke's area": "The brain structure located in the left temporal lobe that is associated with the ability to recognize and understand spoken language."
}

var relatedTerms = {
  "acetylcholine": "neurotransmitter",
  "action potential": "neuron,axon",
  "adrenal glands": "hormone",
  "amygdala": "temporal lobe,limbic system",
  "autonomic nervous system": "somatic nervous system",
  "axon": "neuron",
  "brain stem": "",
  "broca's area": "frontal lobe",
  "ct scan (cat)": "pet scan,eeg (electroencephalography),mri",
  "cell body (soma)": "neuron",
  "central nervous system": "peripheral nervous system",
  "cerebellum": "",
  "chromosome": "gene",
  "dendrite": "neuron",
  "dizygotic twins": "",
  "dopamine": "neurotransmitter",
  "eeg (electroencephalography)": "pet scan,ct scan (cat),mri",
  "endocrine system": "hormone,pituitary gland,adrenal glands",
  "endorphins": "",
  "frontal lobe": "",
  "gaba (gamma-aminobutyric acid)": "neurotransmitter",
  "gene": "chromosome,heritability",
  "heritability": "gene",
  "hippocampus": "",
  "hormone": "endocrine system,pituitary gland,adrenal glands",
  "hypothalamus": "",
  "interneurons": "neuron",
  "kleinfelters/turners syndrome": "gene",
  "lesion": "",
  "limbic system": "amygdala",
  "medulla oblongata": "",
  "monozygotic twins": "",
  "motor neuron": "neuron,reflex arc",
  "mri": "pet scan,ct scan (cat),eeg (electroencephalography)",
  "myelin sheath": "neuron",
  "nature vs. nurture": "",
  "neuron": "dendrite,cell body (soma),axon,myelin sheath,synapse,neurotransmitter,interneurons,motor neuron,sensory neurons",
  "neurotransmitter": "neuron,acetylcholine,gaba (gamma-aminobutyric acid),dopamine,serotonin",
  "occipital lobe": "",
  "parasympathetic nervous system": "sympathetic nervous system",
  "parietal lobe": "",
  "peripheral nervous system": "central nervous system",
  "pet scan": "ct scan (cat),eeg (electroencephalography),mri",
  "pituitary gland": "hormone",
  "pons": "",
  "reflex arc": "sensory neurons,motor neuron",
  "reticular formation": "",
  "left vs. right hemisphere": "",
  "sensory neurons": "neuron,reflex arc,thalamus",
  "serotonin": "neurotransmitter",
  "sex glands": "hormone",
  "somatic nervous system": "autonomic nervous system",
  "sympathetic nervous system": "parasympathetic nervous system",
  "synapse": "neuron",
  "temporal lobe": "amygdala,wernicke's area",
  "terminal button": "neuron, neurotransmitter",
  "thalamus": "sensory neurons",
  "threshold": "sensory neurons",
  "thyroid gland": "hormone",
  "wernicke's area": "temporal lobe",
}

var terms = [];

$(function() {
    for(var t in termsArray) {
      terms.push(t);
      console.log(t);
    }
});

$(function () {
  $('#termBox').on('input', function() {
    update();
  });
});

$(function () {
  $(document).on('click', '.relatedTerm', function(){
      console.log("AGHHHHHHHHHH");
      $('#termBox').val($(this).text());
      update();
  });
});

function update() {
  var value = termsArray[$('#termBox').val().toLowerCase()];
  var related = relatedTerms[$('#termBox').val().toLowerCase()];
  if(typeof value != 'undefined'){
    document.getElementById("define").innerHTML = "<div id=\"leftline\"></div><div id=\"righttext\"><p><span id=\"termText\"><i>" + $('#termBox').val().toLowerCase() + "</i>: </span><span id=\"definitionText\">" + value + "</span></p></div>";
    var height = Math.max($("#righttext").height(), $("#leftline").height());
        $("#leftline").height(height);
        $("#righttext").height(height);

    document.getElementById("define").innerHTML += "<div id=\"relTitle\">Related Terms:</div>";
    var relTerms = related.split(",");
    related = "";
    for(a = 0; a < relTerms.length; a++){
      related += "<a href=\"#\" class=\"relatedTerm\">" + relTerms[a] + "</a>";
    }

    document.getElementById("relTitle").innerHTML += "<div id=\"related terms\">" + related + "</div>";
  }
  else
    document.getElementById("define").innerHTML = "";
}

$(function () {
  var termBoxUpdate = $("#termBox").autocomplete({
      source: terms,
      close: function() {
          //alert('changed');
          update();
      }
   });
   termBoxUpdate.autocomplete('option','close').call(termBoxUpdate);
});
